include:
 - "scan.yml"

stages:
 - build_job
 - test_job

build-image_job:
  image: docker:latest
  services:
    - docker:dind
  stage: build_job
  script:
    - docker info
    - docker pull alpine:3.3
    - docker tag alpine:3.3 demo:1.0
    # archive a running container to a tar file for scanning
    - docker save -o temp.tar demo:1.0
  artifacts:
    expire_in: 1 hours
    paths:
      - temp.tar
  
neuvector_scan:
  stage: test_job
  variables:
    nv_registry_user: admin
    nv_registry_password: Harbor12345
    scan_local_image: "true"
    image_tar: "temp.tar"
    image_repo: "demo"
    image_tag: "1.0"
    nv_registry_url: "harbor.kodyrepo.online"
    nv_scanner_image: "harbor.kodyrepo.online/library/neuvector-scanner:latest"
    nv_registry_user: admin
    nv_registry_password: Harbor12345
    scan_layers: "false"
    high_vul_to_fail: 9
    medium_vul_to_fail: 10
    vul_names_to_fail: "CVE-2020-1971, CVE-2020-1972"
